
model_params:
  objective: 'reg:gamma'
  n_estimators: 256
  learning_rate: 0.05
  max_depth: 6
  max_bin: 32
  subsample: 0.9
  colsample_bytree: 0.8
  eval_metric: 'rmse'
  early_stopping_rounds: 100
  enable_categorical: true

fit_params:
  verbose: 100

categorical_feature:
  - province
  - model
  - bodyType
